name: Intelligent PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y clang-tidy

      - name: Run Static Analysis
        run: |
          flake8 . || true
          clang-tidy **/*.cpp -- -std=c++17 || true

      - name: Run ML Reviewer
        run: |
          python ml_reviewer.py

      - name: Post Comments to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python post_review_comments.py